version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - printenv
      - ls -R
      - cd source/layer
      - ./build_layer.sh
      - cd -
artifacts:
  files:
    - 'php_layer_730.zip'
    - 'solution.yaml'
