AWSTemplateFormatVersion: '2010-09-09'

Description: 'PHP Lambda Layer'

Parameters:
  pSolutionNaming:
    Type: String

Resources:
  rPhp713LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      Description: PHP 7.1.3 Lambda Layer
      LayerName: !Sub '${pSolutionNaming}-php-713-layer'
      Content:
        S3Bucket: !Sub '${pSolutionNaming}-${AWS::AccountId}-${AWS::Region}-s3'
        S3Key: php_layer_713.zip

  rPhp713LambdaLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref rPhp713LambdaLayer
      Principal: !Sub '${AWS::AccountId}'

Outputs:
  oLayerArn:
    Value: !Ref rPhp713LambdaLayer
    Description: 'Arn of the layer'
    Export:
      Name: !Sub '${pSolutionNaming}-layer-arn'

  oLayerS3Key:
    Value: php_layer_713.zip
    Description: 'Physical location to the S3 key of PHP layer file'
    Export:
      Name: !Sub '${pSolutionNaming}-layer-s3-key'
